---
  
  ## MASTER ##
- name: Distribute certificates for masters
  hosts: masters

  vars:
        
    - ansible_ssh_user: "ubuntu"
    - ansible_ssh_common_args: >
          -o ProxyCommand="ssh -W %h:%p -q {{ ansible_ssh_user }}@{{ lookup('env', 'B_HOST') }}" \
          -o ServerAliveInterval=5 \
          -o StrictHostKeyChecking=no
          
  tasks:

    - name: Copy certificates for the masters
      become: yes
      copy:
        src: "{{ item }}"
        dest: "{{ item }}"
      with_items:
        - ca-key.pem
        - ca.pem
        - kubernetes.pem 
        - kubernetes-key.pem 
        - service-account.pem 
        - service-account-key.pem

  ## WORKER ##
- name: Distribute certificates for workers
  hosts: workers

  vars:
        
    - ansible_ssh_user: "ubuntu"
    - ansible_ssh_common_args: >
          -o ProxyCommand="ssh -W %h:%p -q {{ ansible_ssh_user }}@{{ lookup('env', 'B_HOST') }}" \
          -o ServerAliveInterval=5 \
          -o StrictHostKeyChecking=no
          
  tasks:
    - name: Copy certificates for the workers
      become: yes
      copy:
        src: "{{ item }}"
        dest: "{{ item }}"
      with_items:
        - ca.pem 
        - "worker.{{ inventory_hostname }}.pem" 
        - "worker.{{ inventory_hostname }}-key.pem"